Update electronic-design.md
Luos-io/Documentation pull request #104
Opened 2021-03-09 21:23 UTC by Gogopex

- fixed a typo l.7
- rephrased the `Compatible MCUs`section; the grammar is now a bit smoother.

2021-03-10 13:12 UTC, Simonbdy approved these changes
Ok for me for the line 7.
For the line 22, I'll let James review as he rewrote this part earlier I reckon.

2021-03-26 09:16 UTC, jlangbridge requested changes
Suggest "yet supported" on line 22; -> "is not yet supported"

2021-03-26 16:22 UTC, Gogopex commented on src/pages/low/hardware_topics/electronic-design.md
> +Luos can manage any type of microcontrollers as long as they are first added to the library manually. If your microcontroller is not supported yet, please contact us:
```suggestion
Luos can manage any type of microcontrollers as long as they are first added to the library manually. If your microcontroller is not yet supported, please contact us:
```

2021-03-26 16:23 UTC, Gogopex commented on src/pages/low/hardware_topics/electronic-design.md
> +Luos can manage any type of microcontrollers as long as they are first added to the library manually. If your microcontroller is not supported yet, please contact us:
@jlangbridge I do agree this flows better 👍  Feel free to commit the suggestion if this is what you meant 👍

2021-04-19 06:45 UTC, merged