Add warning and MCU family declaration
Luos-io/Documentation pull request #118
Opened 2021-07-23 13:49 UTC by Emanuel-Allely

2021-07-23 14:56 UTC, Simonbdy approved these changes

2021-07-26 09:48 UTC, nicolas-rabault requested changes

2021-07-26 09:48 UTC, nicolas-rabault commented on src/pages/embedded/dev_env/platformio.md
> +-DLUOSHAL= <MCU family>
```
build_flags =
    -DLUOSHAL= <LuosHAL folder>
```

2021-07-26 09:48 UTC, nicolas-rabault commented on src/pages/embedded/dev_env/platformio.md
> +Replace `<MCU family>` with the family of the MCU you are usign, eg. `-DLUOSHAL=STM32F0` for the F0 family.
Replace `<LuosHAL folder>` with the <a href="https://github.com/Luos-io/LuosHAL">Luos HAL</a> folder corresponding to the family of the MCU you are usign, eg. `-DLUOSHAL=STM32F0` for the F0 family.

2021-07-26 11:49 UTC, Emanuel-Allely reviewed
I did the change

2021-07-26 11:51 UTC, nicolas-rabault approved these changes
ok, now you have to fixup your commit and merge ;)

2021-07-27 06:50 UTC, merged