change container to service
Luos-io/Documentation pull request #122
Opened 2021-07-27 16:16 UTC by Salem-Luos

2021-07-28 07:13 UTC, Simonbdy approved these changes
I fixed a few "service" errors (one constant and a few classes in CSS files), and corrected typos from previous comits. All the rest is good.

However, I noticed a few changes in code blocks (functions, variables, constant, etc.) with "service": 
service_t
service_stats_t
Luos_CreateService()
Service_MsgHandler()
RoutingTB_DetectServices()
RoutingTB_IDFromService()
RoutingTB_ServiceIsSensor()
RoutingTB_ConvertServiceToRoutingTable()
RoutingTB_GetLastService()
TemplateState_CreateService()
MAX_SERVICE_NUMBER
service_alias
etc.

I haven't touched any of these (except from updating the uppercases in one constant), so if the code parts are ok for you, you can merge.

2021-08-13 14:44 UTC, Simonbdy requested changes
I made a few comments on rephrasing sentences and improving images' visuals.

2021-08-30 16:09 UTC, BiliouriV commented on src/pages/luos-technology/node/topology.md
> +As mentioned in the previous paragraphs, thanks to [Robus](../node/luos.md), the nodes have the capabilty to communicate with each other. However, Robus is not the only necessity to achieve using thi
I believe that you can totally delete this sentence. I used it as a transition to introduce the idea of topology detection, but you are right it is not clear.  I think that it is not necessary

2021-09-03 15:50 UTC, nicolas-rabault reviewed
I apply my modifications.

2021-09-09 18:04 UTC, Simonbdy reviewed
@nicolas-rabault could you review both new FAQ pages from Thomas?

2021-09-15 11:16 UTC, Simonbdy commented
New comments:
1. In the topology boxes drawn with box-drawing characters, the right stroke is shifted on these pages: pyluos.md, get_started.md, . @nicolas-rabault I think you made these changes, can you please check and fix them?
2.  Various images have various shapes and colors, I will open an issue so that the same codes are used for every image in the docs

2021-09-15 11:36 UTC, Simonbdy commented
I had been able to fix the box-drawing char problem (1) by removing "Source Code Pro" from the `font-family` CSS for the `<code>` tag in file `general.css`.

2021-09-15 12:01 UTC, Simonbdy commented on src/pages/luos-technology/basics/archi.md
> +![](../../../_assets/img/luos_mcu_platform.png)
Addressed in #127 for the next version

2021-09-21 11:39 UTC, nicolas-rabault approved these changes
Realy nice.

2021-09-21 12:02 UTC, Simonbdy approved these changes
Good job!

2021-09-21 12:03 UTC, merged