Add a tutorial about resilient aliases
Luos-io/Documentation pull request #308
Opened 2022-05-19 09:41 UTC by nicolas-rabault

⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

*Add here a description of the modifications you made.*

## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [ ] You requested a technical review.
- [ ] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

2022-05-23 06:08 UTC, Simonbdy requested changes
Very nice and clear.

Here are my comments:
- Two "TODO" are to be replaced at the beginning (19) and at the end (177)
- The function `device.custom_led.rename("custom led")` in line 85 was replaced by `device.led.rename("custom led")`
- The word "somewhere" is too vague, added examples.

2022-05-23 07:28 UTC, Simonbdy approved these changes

2022-06-20 09:49 UTC, BiliouriV commented on tutorials/resilient-alias/resilient-alias.mdx
> +In some developments, you will need to duplicate the same service multiple times. For example, if you are making a robot with multiple motors you could have the exact same board running the exact sam
running the exact same firmware multiple times

2022-06-20 09:51 UTC, BiliouriV commented on tutorials/resilient-alias/resilient-alias.mdx
> +After this creation, your alias may be modified in different ways.
can be modified

2022-06-20 09:54 UTC, BiliouriV commented on tutorials/resilient-alias/resilient-alias.mdx
> +Let's use a simple les service as an example. In the package inititalization, you need to create your service with the associated alias:
led*

2022-06-20 09:57 UTC, BiliouriV commented on tutorials/resilient-alias/resilient-alias.mdx
> +You can find an example of resilient aliases management as a library here: TODO
dont forget this also

2022-06-30 08:14 UTC, BiliouriV approved these changes
Nice and clean work. Bravo!

2022-06-30 09:31 UTC, JeromeGalan reviewed
Good job !

I think, there is too much text to read before the "saving aliases" paragraph.
Maybe we should add some pictures ?

For example :

- After "Luos will add a number at the end of your alias depending on their position from the node performing the detection. This guarantees aliases unicity", we could add a routing table with :
Motor_1  /  Motor_2  /  Motor_3


- After "and to choose a practical alias name such as “left_motor” or “front_sensor”", we could add this kind of pic  (mine is ugly :\\/ ...) :

sensor_10    ---- rename ---->    front_sensor
motor_4    ---- rename ---->    left_motor

2022-07-01 10:58 UTC, Simonbdy approved these changes
ok for me

2022-07-01 13:19 UTC, lorenzi-nicolas approved these changes
Ok for me, the thumbnail has been added

2022-07-01 15:14 UTC, JeromeGalan approved these changes

2022-07-01 15:18 UTC, merged