Feat/bootloader update
Luos-io/Documentation pull request #321
Opened 2022-05-27 18:16 UTC by BiliouriV

⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

*Add here a description of the modifications you made.*
1.Bootloader update
2. stlink troubleshooting page for bootloader
3. typos in stlink page
## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [ ] You requested a technical review.
- [ ] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

2022-05-30 10:27 UTC, nicolas-rabault requested changes

2022-05-30 10:27 UTC, nicolas-rabault commented on docs/tools/boot.mdx
> +If for the communication of the gate with your computer, you are using the ST-Link protocol, and the flashing process is blocked in the last step of flashing with no specific reason, then you may hav
There is no precision regarding the bootloader condition needed to experience this bug. I think you should mention it.

2022-05-30 10:27 UTC, nicolas-rabault commented on docs/tools/boot.mdx
> +To reasure yourself that this is the case, you can try changing the size of your binary by changing some bytes of your code, or you can use an other way to connect your gate, like for example JTAG.
I'm not sure Jtag is the more obvious link here we are talking about serial connection. Why don't we propose an FTDI instead?

2022-05-30 10:27 UTC, nicolas-rabault commented on docs/tools/boot.mdx
> +  | SHARED_MEMORY_SECTOR  | Start sector of shared memory                    |
What if my MCU doesn't have sectors?

2022-05-30 10:27 UTC, nicolas-rabault commented on faq/008.stlink_bootbug.mdx
> +Try to connect your gate to your computer using an other protocol like JTAG, or try to resize the .bin file you want to flash, by slightly changing your application's code.
same JTAG here is not the best way because we are looking for serial. Why not to use FTDI instead?

2022-06-06 12:04 UTC, alexgeron-Luos approved these changes

2022-06-08 09:33 UTC, nicolas-rabault approved these changes
Nice.

2022-06-22 09:41 UTC, Simonbdy approved these changes
Ok for me, thank you.

2022-06-23 06:28 UTC, merged