Feat/advanced doc
Luos-io/Documentation pull request #490
Opened 2022-10-11 08:13 UTC by alexgeron-Luos

⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

*Add here a description of the modifications you made.*

## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [ ] You requested a technical review.
- [ ] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

2022-10-11 11:00 UTC, Simonbdy commented
@alexgeron-Luos can you please provide a description in the part "Pull request's description"? Thanks

2022-10-11 12:58 UTC, K0rdan requested changes

2022-10-11 12:59 UTC, K0rdan commented on docs/advanced-doc/index.mdx
> +Change desc
To remove or update

2022-10-11 16:26 UTC, Simonbdy requested changes
@alexgeron-Luos can you please provide a description in the part "Pull request's description"? Thanks

2022-10-13 08:12 UTC, K0rdan approved these changes

2022-10-17 16:22 UTC, Simonbdy requested changes
I fixed a few typos.

There are some typos to fix on the images as well: 

static/assets/images/advanced-doc/robus/interface/robus-4-3-dark.svg
static/assets/images/advanced-doc/robus/interface/robus-4-3-light.svg
-> Change `receive pending` to `Reception pending`

static/assets/images/advanced-doc/robus/interface/robus-4-3-dark.svg
static/assets/images/advanced-doc/robus/protocol/robus-3-3-light.svg
-> Change `CRC calculate` to `CRC calculated` and `CRC receive` to `CRC received` 

static/assets/images/advanced-doc/robus/topology/robus-2-3-dark.svg
static/assets/images/advanced-doc/robus/topology/robus-2-3-light.svg
-> Change `anothe` to `another`

After that it will be good for me to merge

2022-10-20 06:51 UTC, Simonbdy approved these changes
Ok for me

2022-10-21 06:34 UTC, merged