remove parking page for all tutorials
Luos-io/Documentation pull request #495
Opened 2022-10-17 07:36 UTC by alexgeron-Luos

⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

*Add here a description of the modifications you made.*

## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [ ] You requested a technical review.
- [ ] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

2022-10-18 09:23 UTC, lorenzi-nicolas commented
- [ ] At the level of the card, remove the padding-top to raise the Tutorial, time and level logos and be at the same level as the title
- [ ] For each page, transform the link to match the original page (example for Your first project : /tutorials/get-started/get-started1 > /tutorials/get-started
- [ ] After that, make a 301 redirect between pages (example: /tutorials/get-started/get-started1 to /tutorials/get-started) to avoid a 404 (see table of redirections docs > luos.io/docs). Do this for all the pages concerned
- [ ] Switch trainings and time logos to white for dark mode
- [ ] Edit in the drop-down menu Espressif IDE > "Conect ESP to network" to "Connect ESP to network"

2022-10-27 09:34 UTC, K0rdan requested changes

2022-10-27 09:34 UTC, K0rdan commented on blog/2020-02-13-dc-motor-jungle.mdx
> +[Get Started with Luos](/tutorials/get-started))
Unnecessary `)`

2022-10-27 09:34 UTC, K0rdan commented on blog/2022-08-12-how-to-develop-iot-edge-and-embedded-projects-easier.mdx
> +The main objective is to get the rocket off the ground and exceed the altitude of 32km. The underlying objective of collecting the altitude and checking the flight plan was managed by Luos. The assoc
Missing `)` in the link

2022-10-27 09:34 UTC, K0rdan commented on tutorials/arduino/arduino.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use the `@site` to reference components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/bike-alarm/bike-alarm.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to important components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/bike-alarm/cloud-alarm.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/bootloader/bootloader.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/esp/connect.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/esp/connect.mdx
> +You can find more connection details in the tutorial [Get started: part 3](/tutorials/get-started)3), where you connect the ESP board as a second board in a Luos network, with the pinout described in
Broken link

2022-10-27 09:34 UTC, K0rdan commented on tutorials/esp/esp.mdx
> +<div align="center">
Use Image component

2022-10-27 09:34 UTC, K0rdan commented on tutorials/freertos/freertos.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started2.mdx
> +With your development environment installed in Part 1, you have now taken the control of a Luos app running on your MCU, with Python. The [next part](/tutorials/get-started)3) of this section deals w
Broken link

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started3.mdx
> +The first two parts of the [Get started tutorial](/tutorials/get-started)) are now done. Good work! 💪
`)` not needed

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started3.mdx
> +We will use the same board from the first two parts, but **you also need a second board to create a network**. Supported boards are listed [here](/tutorials/get-started)#setup-development-environment
Broken link

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started4.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/get-started/get-started4.mdx
> +In the previous parts of the [Get started tutorial](/tutorials/get-started)), we used Luos Python SDK (Pyluos) to be able to code the behavior of your embedded device from your computer. This SDK nee
`)` not necessary

2022-10-27 09:34 UTC, K0rdan commented on tutorials/luos-integration/install-ros2.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/luos-integration/ros1-retrocompatibility.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/morse/add-service.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/morse/morse.mdx
> +  <Image src="/assets/images/tutorials/morse/morse-1-5.png" darkSrc="" />
Unnecessary `darkSrc` parameter

2022-10-27 09:34 UTC, K0rdan commented on tutorials/pio/include.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/pio/pio.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/resilient-alias/resilient-alias.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-detection/embedded-app.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-detection/your-first-detection.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-message/send-message.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-message/your-first-message.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-service/create-a-package.mdx
> +Now try to move your led package on another board. Keep only the led package on this second board, and keep the pipe, the gate, and the blinker into the first one. Then wire a OneWire network as you
Broken link

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-service/create-a-package.mdx
> +import Author from '/src/components/school/author/author.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-service/your-first-service.mdx
> +import Introduction from '/src/components/school/article/intro.js';
Use `@site` to import components

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-service/your-first-service.mdx
> +  <img
Use `Image` component

2022-10-27 09:34 UTC, K0rdan commented on tutorials/your-first-service/your-first-service.mdx
> +  <img
Use `Image` component

2022-11-03 09:06 UTC, K0rdan approved these changes

2022-11-03 09:06 UTC, merged