Fix/content blog to update some keywords
Luos-io/Documentation pull request #497
Opened 2022-10-18 15:12 UTC by lorenzi-nicolas

⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

Some keywords or way of presenting our systems were wrong. This modification adapts the used keywords.

## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [ ] You requested a technical review.
- [ ] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

2022-10-18 15:53 UTC, Simonbdy requested changes
A few typos to fix

2022-10-18 15:53 UTC, Simonbdy commented on blog/2022-09-23-create-an-amateur-space-rocket-using-luos.mdx
> +- The MOSI is the line where the follower write and the initiator reads.
`where the followers write` instead of `follower`

2022-10-18 15:53 UTC, Simonbdy commented on blog/2022-09-23-create-an-amateur-space-rocket-using-luos.mdx
> +  - Therefore, this service does a [Luos Detection](/tutorials/your-first-detection). This functionality allows us to have a map of the  and know what and where the other services are. Then, it store
A word is missing here (system)

2022-10-18 15:53 UTC, Simonbdy commented on blog/2022-09-23-create-an-amateur-space-rocket-using-luos.mdx
> +- The MISO is the line where the initiator writes and the followers.
`and the followers read.`

2022-10-20 07:28 UTC, Simonbdy approved these changes
Ok for me. 
Thank you

2022-10-25 07:21 UTC, alexgeron-Luos approved these changes

2022-10-25 07:22 UTC, merged